version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: swiftserver_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: America/Sao_Paulo
    ports:
      - '5432:5432'
    networks:
      - postgres-network
    volumes:
      - ./database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: swiftserver_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@local.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "5050:80"
    networks:
      - postgres-network
    volumes:
      - ./pgadmin:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge
